import { Montserrat } from "next/font/google";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat", // Esta variable debe coincidir con la de tailwind.config
});

export default function RootLayout({ children }) {
  return (
    <html lang="es" className={montserrat.variable}>
      <body className="font-sans antialiased">
        {children}
      </body>
    </html>
  );
}
